version: '3'
services:
  file_box_postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB_NAME: ${DB_DBNAME}
    ports:
      - "5432:5432"

  
  # api:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   command: ["uvicorn", "file_box.api:app", "--host", "0.0.0.0", "--port", "8000"]
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
  #     POSTGRES_HOST: postgres
  #     POSTGRES_PORT: ${POSTGRES_PORT}
  #     DATAPIPE_DOCUMENT_BLOB_BASE_URL: ${DATAPIPE_DOCUMENT_BLOB_BASE_URL}

