"""del: generate path step

Revision ID: b7d94b6311d7
Revises: bc6b3b34f251
Create Date: 2025-04-24 15:34:19.732313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7d94b6311d7'
down_revision: Union[str, None] = 'bc6b3b34f251'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_box_file_data_generate_path_cc7125fe3e_meta')
    op.drop_table('file_box_file_data_meta')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_box_file_data_meta',
    sa.Column('file_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hash', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('create_ts', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('update_ts', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('process_ts', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('delete_ts', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('file_id', 'file_type', name='file_box_file_data_meta_pkey')
    )
    op.create_table('file_box_file_data_generate_path_cc7125fe3e_meta',
    sa.Column('file_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('process_ts', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_success', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('error', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('file_id', 'file_type', name='file_box_file_data_generate_path_cc7125fe3e_meta_pkey')
    )
    # ### end Alembic commands ###
