"""filedata meta

Revision ID: 5e2c16453495
Revises: b7d94b6311d7
Create Date: 2025-04-24 17:09:30.822429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e2c16453495'
down_revision: Union[str, None] = 'b7d94b6311d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_box_file_data_meta',
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('hash', sa.Integer(), nullable=True),
    sa.Column('create_ts', sa.Float(), nullable=True),
    sa.Column('update_ts', sa.Float(), nullable=True),
    sa.Column('process_ts', sa.Float(), nullable=True),
    sa.Column('delete_ts', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('file_id', 'file_type'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_box_file_data_meta', schema='public')
    # ### end Alembic commands ###
