"""init

Revision ID: ed498479cd8c
Revises: 
Create Date: 2025-03-26 16:54:45.499922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed498479cd8c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_box_compress_data',
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('compress_name', sa.String(), nullable=False),
    sa.Column('file_format', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('file_id', 'file_type', 'compress_name')
    )
    op.create_table('file_box_file_data',
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('file_id', 'file_type')
    )
    op.create_table('file_box_file_deleted_data',
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('last_reviewed', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('file_id', 'file_type')
    )
    op.create_table('file_box_image_compress_config',
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('file_format', sa.String(), nullable=False),
    sa.Column('compress_name', sa.String(), nullable=False),
    sa.Column('resampling', sa.String(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('file_type', 'file_format', 'compress_name')
    )
    op.create_table('file_box_image_exclude_moderation',
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('file_id', 'file_type')
    )
    op.create_table('file_box_image_filtered_for_moderation',
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('file_gs_url', sa.String(), nullable=False),
    sa.Column('ls_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('file_id', 'file_type')
    )
    op.create_table('file_box_image_google_moderation_data',
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('google_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('file_id', 'file_type')
    )
    op.create_table('file_box_image_moderation_config',
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('ls_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('file_type')
    )
    op.create_table('file_box_image_moderation_manual',
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('moderation_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_reviewed', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('file_id', 'file_type')
    )
    op.create_table('image_to_moderate_ls_input',
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('google_review_status', sa.String(), nullable=True),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('ls_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('file_id', 'file_type')
    )
    op.create_table('file_box_compress_data_meta',
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('compress_name', sa.String(), nullable=False),
    sa.Column('hash', sa.Integer(), nullable=True),
    sa.Column('create_ts', sa.Float(), nullable=True),
    sa.Column('update_ts', sa.Float(), nullable=True),
    sa.Column('process_ts', sa.Float(), nullable=True),
    sa.Column('delete_ts', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('file_id', 'file_type', 'compress_name'),
    schema='public'
    )
    op.create_table('file_box_file_data_meta',
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('hash', sa.Integer(), nullable=True),
    sa.Column('create_ts', sa.Float(), nullable=True),
    sa.Column('update_ts', sa.Float(), nullable=True),
    sa.Column('process_ts', sa.Float(), nullable=True),
    sa.Column('delete_ts', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('file_id', 'file_type'),
    schema='public'
    )
    op.create_table('file_box_file_raw_meta',
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('hash', sa.Integer(), nullable=True),
    sa.Column('create_ts', sa.Float(), nullable=True),
    sa.Column('update_ts', sa.Float(), nullable=True),
    sa.Column('process_ts', sa.Float(), nullable=True),
    sa.Column('delete_ts', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('file_type', 'file_id'),
    schema='public'
    )
    op.create_table('file_box_image_compress_config_meta',
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('file_format', sa.String(), nullable=False),
    sa.Column('compress_name', sa.String(), nullable=False),
    sa.Column('hash', sa.Integer(), nullable=True),
    sa.Column('create_ts', sa.Float(), nullable=True),
    sa.Column('update_ts', sa.Float(), nullable=True),
    sa.Column('process_ts', sa.Float(), nullable=True),
    sa.Column('delete_ts', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('file_type', 'file_format', 'compress_name'),
    schema='public'
    )
    op.create_table('file_box_image_compressed_meta',
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('compress_name', sa.String(), nullable=False),
    sa.Column('file_format', sa.String(), nullable=False),
    sa.Column('hash', sa.Integer(), nullable=True),
    sa.Column('create_ts', sa.Float(), nullable=True),
    sa.Column('update_ts', sa.Float(), nullable=True),
    sa.Column('process_ts', sa.Float(), nullable=True),
    sa.Column('delete_ts', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('file_type', 'file_id', 'compress_name', 'file_format'),
    schema='public'
    )
    op.create_table('file_box_image_exclude_moderation_meta',
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('hash', sa.Integer(), nullable=True),
    sa.Column('create_ts', sa.Float(), nullable=True),
    sa.Column('update_ts', sa.Float(), nullable=True),
    sa.Column('process_ts', sa.Float(), nullable=True),
    sa.Column('delete_ts', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('file_id', 'file_type'),
    schema='public'
    )
    op.create_table('file_box_image_filtered_for_moderation_meta',
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('hash', sa.Integer(), nullable=True),
    sa.Column('create_ts', sa.Float(), nullable=True),
    sa.Column('update_ts', sa.Float(), nullable=True),
    sa.Column('process_ts', sa.Float(), nullable=True),
    sa.Column('delete_ts', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('file_id', 'file_type'),
    schema='public'
    )
    op.create_table('file_box_image_google_moderation_data_meta',
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('hash', sa.Integer(), nullable=True),
    sa.Column('create_ts', sa.Float(), nullable=True),
    sa.Column('update_ts', sa.Float(), nullable=True),
    sa.Column('process_ts', sa.Float(), nullable=True),
    sa.Column('delete_ts', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('file_id', 'file_type'),
    schema='public'
    )
    op.create_table('file_box_image_moderation_config_meta',
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('hash', sa.Integer(), nullable=True),
    sa.Column('create_ts', sa.Float(), nullable=True),
    sa.Column('update_ts', sa.Float(), nullable=True),
    sa.Column('process_ts', sa.Float(), nullable=True),
    sa.Column('delete_ts', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('file_type'),
    schema='public'
    )
    op.create_table('file_raw_save_to_store_75bf3853d3_meta',
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('process_ts', sa.Float(), nullable=True),
    sa.Column('is_success', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('file_id', 'file_type'),
    schema='public'
    )
    op.create_table('image_compress_b594ec81d8_meta',
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('file_format', sa.String(), nullable=False),
    sa.Column('compress_name', sa.String(), nullable=False),
    sa.Column('process_ts', sa.Float(), nullable=True),
    sa.Column('is_success', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('file_id', 'file_type', 'file_format', 'compress_name'),
    schema='public'
    )
    op.create_table('image_filter_for_moderation_06752517c9_meta',
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('process_ts', sa.Float(), nullable=True),
    sa.Column('is_success', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('file_id', 'file_type'),
    schema='public'
    )
    op.create_table('image_google_moderation_1762c0bc15_meta',
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('process_ts', sa.Float(), nullable=True),
    sa.Column('is_success', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('file_id', 'file_type'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_google_moderation_1762c0bc15_meta', schema='public')
    op.drop_table('image_filter_for_moderation_06752517c9_meta', schema='public')
    op.drop_table('image_compress_b594ec81d8_meta', schema='public')
    op.drop_table('file_raw_save_to_store_75bf3853d3_meta', schema='public')
    op.drop_table('file_box_image_moderation_config_meta', schema='public')
    op.drop_table('file_box_image_google_moderation_data_meta', schema='public')
    op.drop_table('file_box_image_filtered_for_moderation_meta', schema='public')
    op.drop_table('file_box_image_exclude_moderation_meta', schema='public')
    op.drop_table('file_box_image_compressed_meta', schema='public')
    op.drop_table('file_box_image_compress_config_meta', schema='public')
    op.drop_table('file_box_file_raw_meta', schema='public')
    op.drop_table('file_box_file_data_meta', schema='public')
    op.drop_table('file_box_compress_data_meta', schema='public')
    op.drop_table('image_to_moderate_ls_input')
    op.drop_table('file_box_image_moderation_manual')
    op.drop_table('file_box_image_moderation_config')
    op.drop_table('file_box_image_google_moderation_data')
    op.drop_table('file_box_image_filtered_for_moderation')
    op.drop_table('file_box_image_exclude_moderation')
    op.drop_table('file_box_image_compress_config')
    op.drop_table('file_box_file_deleted_data')
    op.drop_table('file_box_file_data')
    op.drop_table('file_box_compress_data')
    # ### end Alembic commands ###
